---

- name: Install AWS Load Balancer Controller
  gather_facts: false
  hosts: localhost
  vars:
    aws_region: us-east-1
    aws_account_id: 968225077300
    vpc_id: vpc-067baffd4078a00f3
    eks_cluster_name: devops-na-nuvem-week-eks-cluster
    alb_controller_policy_name: AWSLoadBalancerControllerIAMPolicy
  tasks:

    - name: Download IAM Policy
      shell: curl https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.7.2/docs/install/iam_policy.json
      register: iam_policy_output

    - name: Create Policy
      shell: |
        aws iam create-policy \
          --policy-name {{alb_controller_policy_name}} \
          --policy-document '{{iam_policy_output.stdout}}'
      register: iam_policy_creation_output

    - name: Create Policy (Output)
      debug:
        var: iam_policy_creation_output

    - name: Create IAM Role 
      shell: |
        eksctl create iamserviceaccount \
          --cluster={{eks_cluster_name}} \
          --namespace=kube-system \
          --name=aws-load-balancer-controller \
          --role-name AmazonEKSLoadBalancerControllerRole \
          --attach-policy-arn=arn:aws:iam::{{aws_account_id}}:policy/{{alb_controller_policy_name}} \
          --approve
      register: iam_role_creation_output

    - name: Create IAM Role (Output)
      debug:
        var: iam_role_creation_output

    - name: Add Helm Chart
      shell: |
        helm repo add eks https://aws.github.io/eks-charts
          helm repo update eks

    - name: Install Load Balancer Controller
      shell: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
          -n kube-system \
          --set clusterName={{eks_cluster_name}} \
          --set serviceAccount.create=false \
          --set region={{aws_region}} \
          --set vpcId={{vpc_id}} \
          --set serviceAccount.name=aws-load-balancer-controller
      register: alb_controller_installation_output

    - name: Install Load Balancer Controller (Output)
      debug:
        var: alb_controller_installation_output